const bcrypt = require('bcryptjs');
const env = require('../config/env');

const demoStore = {
  users: [
    {
      id: 1,
      fullName: env.demo.teacher.fullName,
      username: env.demo.teacher.username,
      email: env.demo.teacher.email,
      passwordHash: bcrypt.hashSync(env.demo.teacher.password, env.security.bcryptRounds),
      role: 'TEACHER',
    },
    {
      id: 2,
      fullName: env.demo.student.fullName,
      username: env.demo.student.username,
      email: env.demo.student.email,
      passwordHash: bcrypt.hashSync(env.demo.student.password, env.security.bcryptRounds),
      role: 'STUDENT',
    },
    {
      id: 3,
      fullName: env.demo.parent.fullName,
      username: env.demo.parent.username,
      email: env.demo.parent.email,
      passwordHash: bcrypt.hashSync(env.demo.parent.password, env.security.bcryptRounds),
      role: 'PARENT',
    },
  ],
  classes: [
    { id: 1, name: 'English 6 - T2/T5', grade: 6, schoolYear: env.academic.defaultSchoolYear, schedule: 'Thứ 2, Thứ 5 • 17:30', status: 'ACTIVE', teacherId: 1 },
    { id: 2, name: 'English 7 - T3/T6', grade: 7, schoolYear: env.academic.defaultSchoolYear, schedule: 'Thứ 3, Thứ 6 • 17:30', status: 'ACTIVE', teacherId: 1 },
    { id: 3, name: 'English 8 - T2/T5', grade: 8, schoolYear: env.academic.defaultSchoolYear, schedule: 'Thứ 2, Thứ 5 • 19:00', status: 'ACTIVE', teacherId: 1 },
    { id: 4, name: 'English 9 - T3/T6', grade: 9, schoolYear: env.academic.defaultSchoolYear, schedule: 'Thứ 3, Thứ 6 • 19:00', status: 'ACTIVE', teacherId: 1 },
  ],
  students: [
    { id: 1, studentCode: 'Y6_HS1', fullName: 'Nguyễn Minh Anh', school: 'THCS Nguyễn Trãi', schoolClass: '6A2', parentPhone: '0900000001', status: 'ACTIVE', classIds: [1], averageScore: 8.6, attendanceRate: 96 },
    { id: 2, studentCode: 'Y6_HS2', fullName: 'Trần Gia Hân', school: 'THCS Lê Lợi', schoolClass: '6A1', parentPhone: '0900000002', status: 'ACTIVE', classIds: [1], averageScore: 7.8, attendanceRate: 92 },
    { id: 3, studentCode: 'Y7_HS3', fullName: 'Lê Hoàng Nam', school: 'THCS Văn Quán', schoolClass: '7A3', parentPhone: '0900000003', status: 'ACTIVE', classIds: [2], averageScore: 7.1, attendanceRate: 88 },
    { id: 4, studentCode: 'Y7_HS4', fullName: 'Phạm Khánh Linh', school: 'THCS Mỗ Lao', schoolClass: '7A1', parentPhone: '0900000004', status: 'ACTIVE', classIds: [2], averageScore: 9.0, attendanceRate: 100 },
    { id: 5, studentCode: 'Y8_HS5', fullName: 'Vũ Đức Minh', school: 'THCS Nguyễn Du', schoolClass: '8A4', parentPhone: '0900000005', status: 'ACTIVE', classIds: [3], averageScore: 6.9, attendanceRate: 84 },
    { id: 6, studentCode: 'Y8_HS6', fullName: 'Đỗ Ngọc Mai', school: 'THCS Nguyễn Trãi', schoolClass: '8A2', parentPhone: '0900000006', status: 'ACTIVE', classIds: [3], averageScore: 8.2, attendanceRate: 95 },
    { id: 7, studentCode: 'Y9_HS7', fullName: 'Bùi Quang Huy', school: 'THCS Lê Quý Đôn', schoolClass: '9A1', parentPhone: '0900000007', status: 'ACTIVE', classIds: [4], averageScore: 7.5, attendanceRate: 90 },
    { id: 8, studentCode: 'Y9_HS8', fullName: 'Hoàng Thu Trang', school: 'THCS Văn Khê', schoolClass: '9A2', parentPhone: '0900000008', status: 'ACTIVE', classIds: [4], averageScore: 8.8, attendanceRate: 98 },
  ],
  studentAccounts: [
    { userId: 2, studentId: 3 },
  ],
  parentStudents: [
    { parentUserId: 3, studentId: 3, relationship: 'Bố/Mẹ' },
    { parentUserId: 3, studentId: 5, relationship: 'Bố/Mẹ' },
  ],
  parentNotificationReads: [],
  lessons: [
    { id: 1, classId: 1, unitName: 'Unit 1', title: 'My New School', summary: 'Từ vựng trường học, giới thiệu bản thân và cấu trúc hiện tại đơn.', content: 'Ôn từ vựng về trường học, luyện giới thiệu lớp học và thực hành Present Simple.', status: 'PUBLISHED', sortOrder: 1, publishedAt: '2026-08-18T08:00:00+07:00' },
    { id: 2, classId: 2, unitName: 'Unit 2', title: 'Healthy Living', summary: 'Past Simple, thói quen tốt và luyện nghe.', content: 'Học sinh luyện Past Simple qua tình huống cuối tuần, sau đó nghe đoạn hội thoại về healthy habits.', status: 'PUBLISHED', sortOrder: 2, publishedAt: '2026-08-20T08:00:00+07:00' },
    { id: 3, classId: 3, unitName: 'Unit 1', title: 'Teen Life', summary: 'Reading, vocabulary và listening theo chủ đề đời sống tuổi teen.', content: 'Đọc hiểu ngắn, mở rộng từ vựng và luyện nghe lấy ý chính.', status: 'PUBLISHED', sortOrder: 1, publishedAt: '2026-08-20T08:00:00+07:00' },
    { id: 4, classId: 4, unitName: 'Review', title: 'Grammar Exam Review', summary: 'Ôn tập ngữ pháp trọng tâm trước bài kiểm tra.', content: 'Tổng hợp cấu trúc và lỗi thường gặp.', status: 'DRAFT', sortOrder: 99, publishedAt: null },
  ],
  assignments: [
    { id: 1, title: 'Unit 1 - Vocabulary', classId: 1, lessonId: 1, description: 'Ôn từ vựng Unit 1.', instructions: 'Hoàn thành 20 từ và viết 5 câu ví dụ.', dueAt: '2026-08-26T22:00:00+07:00', submitted: 12, total: 18, type: 'HOMEWORK', status: 'PUBLISHED', maxScore: 10 },
    { id: 2, title: 'Unit 2 - Grammar', classId: 2, lessonId: 2, description: 'Luyện Past Simple.', instructions: 'Viết 10 câu về hoạt động cuối tuần bằng Past Simple.', dueAt: '2026-08-27T22:00:00+07:00', submitted: 14, total: 20, type: 'HOMEWORK', status: 'PUBLISHED', maxScore: 10 },
    { id: 3, title: 'Reading Practice', classId: 3, lessonId: 3, description: 'Bài đọc Teen Life.', instructions: 'Đọc đoạn văn và trả lời câu hỏi bằng câu đầy đủ.', dueAt: '2026-08-28T22:00:00+07:00', submitted: 10, total: 16, type: 'HOMEWORK', status: 'PUBLISHED', maxScore: 10 },
    { id: 4, title: 'Listening - Healthy Living', classId: 2, lessonId: 2, description: 'Listening practice.', instructions: 'Nghe audio 2 lần và ghi lại 5 ý chính.', dueAt: '2026-08-30T20:00:00+07:00', submitted: 9, total: 20, type: 'PRACTICE', status: 'PUBLISHED', maxScore: 10 },
    { id: 5, title: 'Quiz Unit 2', classId: 2, lessonId: 2, description: 'Quiz ôn tập Unit 2.', instructions: 'Hoàn thành trước giờ học tiếp theo.', dueAt: '2026-09-01T19:00:00+07:00', submitted: 0, total: 20, type: 'QUIZ', status: 'PUBLISHED', maxScore: 10 },
    { id: 6, title: 'Vocabulary Review', classId: 3, lessonId: 3, description: 'Ôn từ vựng Teen Life.', instructions: 'Viết nghĩa và 1 câu ví dụ cho mỗi từ.', dueAt: '2026-08-29T21:00:00+07:00', submitted: 7, total: 16, type: 'HOMEWORK', status: 'PUBLISHED', maxScore: 10 },
  ],
  assignmentSubmissions: [
    { assignmentId: 2, studentId: 3, status: 'GRADED', score: 8.0, submittedAt: '2026-08-26T19:15:00+07:00', submissionText: 'Last weekend I visited my grandparents and helped my mother...', teacherFeedback: 'Nội dung tốt, chú ý thêm động từ bất quy tắc.' },
    { assignmentId: 4, studentId: 3, status: 'NOT_STARTED', score: null, submittedAt: null, submissionText: '', teacherFeedback: '' },
    { assignmentId: 5, studentId: 3, status: 'NOT_STARTED', score: null, submittedAt: null, submissionText: '', teacherFeedback: '' },
    { assignmentId: 3, studentId: 5, status: 'LATE', score: null, submittedAt: null, submissionText: '', teacherFeedback: '' },
    { assignmentId: 6, studentId: 5, status: 'NOT_STARTED', score: null, submittedAt: null, submissionText: '', teacherFeedback: '' },
  ],
  assignmentSubmissionAssets: [],
  studentScores: [
    { id: 1, studentId: 3, title: 'Quiz Unit 1', category: 'Grammar', score: 7.5, maxScore: 10, recordedAt: '2026-08-05' },
    { id: 2, studentId: 3, title: 'Vocabulary Unit 1', category: 'Vocabulary', score: 8.2, maxScore: 10, recordedAt: '2026-08-10' },
    { id: 3, studentId: 3, title: 'Reading Practice', category: 'Reading', score: 7.0, maxScore: 10, recordedAt: '2026-08-16' },
    { id: 4, studentId: 3, title: 'Speaking Check', category: 'Speaking', score: 6.4, maxScore: 10, recordedAt: '2026-08-21' },
    { id: 5, studentId: 3, title: 'Unit 2 - Grammar', category: 'Grammar', score: 8.0, maxScore: 10, recordedAt: '2026-08-26' },
    { id: 6, studentId: 5, title: 'Quiz Unit 1', category: 'Grammar', score: 6.5, maxScore: 10, recordedAt: '2026-08-06' },
    { id: 7, studentId: 5, title: 'Reading Practice', category: 'Reading', score: 7.2, maxScore: 10, recordedAt: '2026-08-15' },
    { id: 8, studentId: 5, title: 'Listening Check', category: 'Listening', score: 6.0, maxScore: 10, recordedAt: '2026-08-23' },
  ],
  assignmentSkills: [
    { assignmentId: 2, skillCode: 'GRAMMAR', weight: 1 },
    { assignmentId: 4, skillCode: 'LISTENING', weight: 1 },
  ],
  questionSkills: [
    { questionId: 1, skillCode: 'GRAMMAR', weight: 1 },
  ],
  studentSkills: [
    { studentId: 3, skill: 'Vocabulary', score: 7.8 },
    { studentId: 3, skill: 'Grammar', score: 7.2 },
    { studentId: 3, skill: 'Listening', score: 6.4 },
    { studentId: 3, skill: 'Speaking', score: 6.0 },
    { studentId: 3, skill: 'Reading', score: 7.6 },
    { studentId: 3, skill: 'Writing', score: 6.8 },
    { studentId: 5, skill: 'Vocabulary', score: 7.0 },
    { studentId: 5, skill: 'Grammar', score: 6.3 },
    { studentId: 5, skill: 'Listening', score: 5.8 },
    { studentId: 5, skill: 'Speaking', score: 6.2 },
    { studentId: 5, skill: 'Reading', score: 7.1 },
    { studentId: 5, skill: 'Writing', score: 6.0 },
  ],
  teacherNotes: [
    { id: 1, studentId: 3, classSessionId: 1, category: 'PROGRESS', isParentVisible: true, note: 'Nam có tiến bộ ở Grammar. Cần luyện nghe 10–15 phút mỗi ngày và chủ động hơn trong phần Speaking.', createdAt: '2026-08-25', author: env.demo.teacher.fullName },
    { id: 2, studentId: 5, classSessionId: 2, category: 'HOMEWORK', isParentVisible: true, note: 'Minh cần hoàn thành bài đúng hạn và ôn lại cấu trúc câu cơ bản. Listening đang là kỹ năng cần ưu tiên.', createdAt: '2026-08-24', author: env.demo.teacher.fullName },
  ],
  classSessions: [
    { id: 1, classId: 2, teacherId: 1, sessionDate: '2026-08-25', startTime: '17:30', endTime: '19:00', topic: 'Unit 2 – Past Simple & Speaking', lessonSummary: 'Ôn Past Simple, luyện hỏi đáp về hoạt động cuối tuần và speaking theo cặp.', homework: 'Workbook Unit 2 trang 24–25; luyện nghe 10 phút.', sessionGoal: 'Củng cố Past Simple và speaking theo cặp.', teacherSummary: 'Đa số học sinh nắm được cấu trúc. Cần hỗ trợ thêm nhóm yếu phần động từ bất quy tắc.', parentSummary: 'Lớp đã ôn Past Simple và luyện nói theo cặp. Vui lòng nhắc học sinh hoàn thành Workbook.', nextSessionPlan: 'Listening Unit 2 và chữa homework.', parentPublished: true, completedAt: '2026-08-25T19:00:00+07:00', status: 'COMPLETED' },
    { id: 2, classId: 3, teacherId: 1, sessionDate: '2026-08-26', startTime: '19:00', endTime: '20:30', topic: 'Unit 1 – Teen Life & Listening', lessonSummary: 'Reading ngắn, từ vựng Teen Life, nghe ý chính và thảo luận nhóm.', homework: 'Vocabulary Review và Listening Practice.', status: 'IN_PROGRESS' },
    { id: 3, classId: 4, teacherId: 1, sessionDate: '2026-08-27', startTime: '19:00', endTime: '20:30', topic: 'Exam Review – Grammar', lessonSummary: 'Ôn cấu trúc trọng tâm trước bài kiểm tra.', homework: 'Hoàn thành Exam Review.', status: 'PLANNED' },
  ],
  sessionAttendance: [
    { sessionId: 1, studentId: 3, status: 'PRESENT', note: '' },
    { sessionId: 1, studentId: 4, status: 'PRESENT', note: '' },
    { sessionId: 2, studentId: 5, status: 'LATE', note: 'Đến muộn 10 phút' },
    { sessionId: 2, studentId: 6, status: 'PRESENT', note: '' },
  ],
  questions: [
    { id: 1, gradeId: 7, grade: 7, lessonId: 2, questionType: 'MULTIPLE_CHOICE', stem: 'Yesterday, she ___ to the park with her friends.', correctAnswer: '', explanation: 'Past Simple của go là went.', difficulty: 'EASY', defaultPoints: 1, status: 'PUBLISHED' },
    { id: 2, gradeId: 7, grade: 7, lessonId: 2, questionType: 'TRUE_FALSE', stem: 'Getting enough sleep is a healthy habit.', correctAnswer: '', explanation: 'Ngủ đủ giấc là một thói quen tốt cho sức khỏe.', difficulty: 'EASY', defaultPoints: 1, status: 'PUBLISHED' },
    { id: 3, gradeId: 7, grade: 7, lessonId: 2, questionType: 'FILL_BLANK', stem: 'Complete the sentence: I ___ my grandparents last weekend. (visit)', correctAnswer: 'visited', explanation: 'Động từ visit ở Past Simple thêm -ed.', difficulty: 'MEDIUM', defaultPoints: 1, status: 'PUBLISHED' },
    { id: 4, gradeId: 7, grade: 7, lessonId: 2, questionType: 'MULTIPLE_CHOICE', stem: 'Which word is closest in meaning to “healthy”?', correctAnswer: '', explanation: 'Healthy có nghĩa là khỏe mạnh / good for your health.', difficulty: 'MEDIUM', defaultPoints: 1, status: 'PUBLISHED' },
    { id: 5, gradeId: 8, grade: 8, lessonId: 3, questionType: 'MULTIPLE_CHOICE', stem: 'Teenagers often use social media to ___ with friends.', correctAnswer: '', explanation: 'Connect with friends là cụm từ phù hợp.', difficulty: 'EASY', defaultPoints: 1, status: 'PUBLISHED' },
    { id: 6, gradeId: 7, grade: 7, lessonId: 2, questionType: 'FILL_BLANK', stem: 'Complete: She ___ not go to school yesterday. (do)', correctAnswer: 'did', explanation: 'Phủ định Past Simple dùng did not + V.', difficulty: 'HARD', defaultPoints: 2, status: 'PUBLISHED' },
    { id: 7, gradeId: 7, grade: 7, lessonId: 2, questionType: 'ESSAY', stem: 'Write 80–100 words about what you did last weekend.', correctAnswer: 'Use Past Simple, clear organization, and suitable vocabulary.', explanation: 'Chấm theo nội dung, ngữ pháp, từ vựng và bố cục.', difficulty: 'MEDIUM', defaultPoints: 4, status: 'PUBLISHED' },
  ],
  questionOptions: [
    { id: 1, questionId: 1, optionKey: 'A', optionText: 'go', isCorrect: false, sortOrder: 1 },
    { id: 2, questionId: 1, optionKey: 'B', optionText: 'went', isCorrect: true, sortOrder: 2 },
    { id: 3, questionId: 1, optionKey: 'C', optionText: 'goes', isCorrect: false, sortOrder: 3 },
    { id: 4, questionId: 1, optionKey: 'D', optionText: 'going', isCorrect: false, sortOrder: 4 },
    { id: 5, questionId: 2, optionKey: 'A', optionText: 'True', isCorrect: true, sortOrder: 1 },
    { id: 6, questionId: 2, optionKey: 'B', optionText: 'False', isCorrect: false, sortOrder: 2 },
    { id: 7, questionId: 4, optionKey: 'A', optionText: 'good for your health', isCorrect: true, sortOrder: 1 },
    { id: 8, questionId: 4, optionKey: 'B', optionText: 'very expensive', isCorrect: false, sortOrder: 2 },
    { id: 9, questionId: 4, optionKey: 'C', optionText: 'difficult to learn', isCorrect: false, sortOrder: 3 },
    { id: 10, questionId: 4, optionKey: 'D', optionText: 'very noisy', isCorrect: false, sortOrder: 4 },
    { id: 11, questionId: 5, optionKey: 'A', optionText: 'connect', isCorrect: true, sortOrder: 1 },
    { id: 12, questionId: 5, optionKey: 'B', optionText: 'delete', isCorrect: false, sortOrder: 2 },
    { id: 13, questionId: 5, optionKey: 'C', optionText: 'sleep', isCorrect: false, sortOrder: 3 },
    { id: 14, questionId: 5, optionKey: 'D', optionText: 'cook', isCorrect: false, sortOrder: 4 },
  ],
  exams: [
    { id: 1, classId: 2, title: 'Unit 2 Online Quiz', description: 'Kiểm tra nhanh Past Simple và Healthy Living.', instructions: 'Đọc kỹ câu hỏi. Hệ thống tự động lưu đáp án.', durationMinutes: 20, startAt: '2026-08-27T08:00:00+07:00', endAt: '2026-09-30T22:00:00+07:00', maxAttempts: 2, showResult: true, selectionMode: 'MANUAL', randomizeQuestions: false, randomizeOptions: false, passScorePercent: 50, status: 'PUBLISHED', publishedAt: '2026-08-27T08:00:00+07:00' },
  ],
  examQuestions: [
    { examId: 1, questionId: 1, sortOrder: 1, points: 1 },
    { examId: 1, questionId: 2, sortOrder: 2, points: 1 },
    { examId: 1, questionId: 3, sortOrder: 3, points: 1 },
    { examId: 1, questionId: 4, sortOrder: 4, points: 1 },
    { examId: 1, questionId: 6, sortOrder: 5, points: 2 },
    { examId: 1, questionId: 7, sortOrder: 6, points: 4 },
  ],
  examAttempts: [],
  examAnswers: [],
  examPoolRules: [],
  examQuestionSnapshots: [],
  examAttemptQuestions: [],
  examStudentOverrides: [],
  attendanceRecords: [
    { studentId: 3, date: '2026-08-11', status: 'PRESENT' },
    { studentId: 3, date: '2026-08-14', status: 'PRESENT' },
    { studentId: 3, date: '2026-08-18', status: 'LATE' },
    { studentId: 3, date: '2026-08-21', status: 'PRESENT' },
    { studentId: 3, date: '2026-08-25', status: 'PRESENT' },
    { studentId: 5, date: '2026-08-10', status: 'PRESENT' },
    { studentId: 5, date: '2026-08-13', status: 'ABSENT_EXCUSED' },
    { studentId: 5, date: '2026-08-17', status: 'LATE' },
    { studentId: 5, date: '2026-08-20', status: 'PRESENT' },
    { studentId: 5, date: '2026-08-24', status: 'ABSENT' },
  ],
  materials: [
    { id: 1, classId: 2, lessonId: 2, unit: 'Unit 2', title: 'Grammar: Past Simple', type: 'PDF', description: 'Tóm tắt cấu trúc và bài tập Past Simple.', resourceUrl: 'https://example.com/materials/past-simple.pdf', status: 'PUBLISHED', publishedAt: '2026-08-20' },
    { id: 2, classId: 2, lessonId: 2, unit: 'Unit 2', title: 'Listening: Healthy Living', type: 'AUDIO', description: 'Audio luyện nghe chủ đề Healthy Living.', resourceUrl: 'https://example.com/materials/healthy-living.mp3', status: 'PUBLISHED', publishedAt: '2026-08-23' },
    { id: 3, classId: 2, lessonId: 2, unit: 'Unit 2', title: 'Vocabulary Flashcards', type: 'FLASHCARD', description: 'Bộ flashcard từ vựng Unit 2.', resourceUrl: 'https://example.com/materials/unit2-flashcards', status: 'PUBLISHED', publishedAt: '2026-08-24' },
    { id: 4, classId: 3, lessonId: 3, unit: 'Unit 1', title: 'Reading: Teen Life', type: 'PDF', description: 'Reading worksheet.', resourceUrl: 'https://example.com/materials/teen-life-reading.pdf', status: 'PUBLISHED', publishedAt: '2026-08-20' },
    { id: 5, classId: 3, lessonId: 3, unit: 'Unit 1', title: 'Vocabulary Review', type: 'FLASHCARD', description: 'Ôn tập từ vựng Teen Life.', resourceUrl: 'https://example.com/materials/teen-life-vocabulary', status: 'PUBLISHED', publishedAt: '2026-08-22' },
  ],
};

module.exports = demoStore;
