const env=require('../../config/env');
const repo=require('./exam.repository');
const questionRepo=require('../questions/question.repository');
const questionService=require('../questions/question.service');
const classService=require('../classes/class.service');
async function canAccess(exam,userId,isAdmin){return Boolean(exam&&(isAdmin||await classService.getClassDetail(exam.classId,userId,false)));}
function clean(v){return String(v||'').trim();}
function dateValue(v){const t=clean(v);if(!t)return'';const d=new Date(t);if(Number.isNaN(d.getTime()))throw new Error('INVALID_DATE');return d.toISOString();}
function ids(value){const list=Array.isArray(value)?value:[value];return [...new Set(list.map(Number).filter((x)=>Number.isInteger(x)&&x>0))];}
async function list(userId,isAdmin=false){const classes=isAdmin?await repo.findClasses():await classService.getClasses(userId,false);const allowed=new Set(classes.map(c=>Number(c.id)));return{exams:(await repo.findAll()).filter(e=>isAdmin||allowed.has(Number(e.classId)))};}
async function newForm(id=null,userId,isAdmin=false){const classes=isAdmin?await repo.findClasses():await classService.getClasses(userId,false);const exam=id?await repo.findById(id):null;const questionData=await questionService.list({status:'PUBLISHED'},userId,isAdmin);return{classes,questions:questionData.questions,exam:await canAccess(exam,userId,isAdmin)?exam:null};}
function parseExam(body){const classId=Number(body.classId),title=clean(body.title),durationMinutes=Number(body.durationMinutes||env.exam.defaultDurationMinutes),maxAttempts=Number(body.maxAttempts||env.exam.defaultMaxAttempts),questionIds=ids(body.questionIds);if(!Number.isInteger(classId)||classId<=0)throw new Error('CLASS_REQUIRED');if(!title)throw new Error('TITLE_REQUIRED');if(!Number.isInteger(durationMinutes)||durationMinutes<1||durationMinutes>env.exam.maxDurationMinutes)throw new Error('INVALID_DURATION');if(!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>env.exam.maxAttempts)throw new Error('INVALID_ATTEMPTS');if(!questionIds.length)throw new Error('QUESTIONS_REQUIRED');const startAt=dateValue(body.startAt),endAt=dateValue(body.endAt);if(startAt&&endAt&&new Date(endAt)<=new Date(startAt))throw new Error('INVALID_WINDOW');return{classId,title,description:clean(body.description),instructions:clean(body.instructions),durationMinutes,startAt,endAt,maxAttempts,showResult:Array.isArray(body.showResult) ? body.showResult.some(v=>['on','true','1'].includes(String(v))) : (body.showResult===undefined ? env.exam.defaultShowResult : ['on','true','1'].includes(String(body.showResult))),questionIds};}
async function create(body,userId,isAdmin=false){const data=parseExam(body);if(!await classService.getClassDetail(data.classId,userId,isAdmin))throw new Error('CLASS_NOT_FOUND');const questions=(await questionService.list({status:'PUBLISHED'},userId,isAdmin)).questions;const allowed=new Set(questions.map((question)=>Number(question.id)));if(data.questionIds.some((id)=>!allowed.has(Number(id))))throw new Error('INVALID_QUESTIONS');return repo.create(data,userId);}
async function update(id,body,userId,isAdmin=false){if(!await detail(id,userId,isAdmin))throw new Error('EXAM_NOT_FOUND');const data=parseExam(body);if(!await classService.getClassDetail(data.classId,userId,isAdmin))throw new Error('CLASS_NOT_FOUND');const questions=(await questionService.list({status:'PUBLISHED'},userId,isAdmin)).questions;const allowed=new Set(questions.map((question)=>Number(question.id)));if(data.questionIds.some((questionId)=>!allowed.has(Number(questionId))))throw new Error('INVALID_QUESTIONS');return repo.update(id,data);}
async function detail(id,userId,isAdmin=false){const exam=await repo.findById(id);return await canAccess(exam,userId,isAdmin)?exam:null;}
async function publish(id,userId,isAdmin=false){const exam=await detail(id,userId,isAdmin);if(!exam)throw new Error('EXAM_NOT_FOUND');if(!exam.questions.length)throw new Error('EXAM_EMPTY');return repo.publish(id);}
async function close(id,userId,isAdmin=false){if(!await detail(id,userId,isAdmin))throw new Error('EXAM_NOT_FOUND');return repo.close(id);}
async function studentList(userId){const exams=await repo.findStudentExams(userId);const now=Date.now();return exams.map((e)=>{const start=e.startAt?new Date(e.startAt).getTime():null,end=e.endAt?new Date(e.endAt).getTime():null;let availability=e.status==='CLOSED'?'CLOSED':'OPEN';if(availability!=='CLOSED'&&start&&now<start)availability='UPCOMING';if(availability!=='CLOSED'&&end&&now>end)availability='CLOSED';if(Number(e.attempts||0)>=Number(e.maxAttempts||1)&&e.lastStatus!=='IN_PROGRESS')availability='DONE';return{...e,availability};});}
async function start(id,userId){return repo.startAttempt(id,userId);}
async function attempt(id,userId){const data=await repo.findAttempt(id,userId);if(!data)return null;const map=new Map(data.answers.map((a)=>[Number(a.questionId),a]));data.exam.questions=data.exam.questions.map((q)=>({...q,answer:map.get(Number(q.id))||{selectedOptionId:null,answerText:'',gradingStatus:'NOT_GRADED',teacherFeedback:'',awardedScore:null}}));data.remainingMs=Math.max(0,new Date(data.deadline).getTime()-Date.now());return data;}
async function saveAnswer(attemptId,userId,body){return repo.saveAnswer(attemptId,userId,{questionId:Number(body.questionId),selectedOptionId:body.selectedOptionId?Number(body.selectedOptionId):null,answerText:clean(body.answerText)});}
async function submit(attemptId,userId,body){const data=await repo.findAttempt(attemptId,userId);if(!data)throw new Error('ATTEMPT_NOT_FOUND');const expired=Date.now()>new Date(data.deadline).getTime();let auto=body.autoSubmitted==='1'||expired;if(!expired){try{for(const q of data.exam.questions){const key=`answer_${q.id}`;const raw=body[key];if(['FILL_BLANK','ESSAY'].includes(q.questionType))await repo.saveAnswer(attemptId,userId,{questionId:q.id,answerText:clean(raw),selectedOptionId:null});else if(raw)await repo.saveAnswer(attemptId,userId,{questionId:q.id,selectedOptionId:Number(raw),answerText:''});}}catch(error){if(error.message==='ATTEMPT_NOT_ACTIVE'||error.message==='ATTEMPT_EXPIRED')auto=true;else throw error;}}return repo.gradeAttempt(attemptId,userId,auto);}
async function gradeForm(examId,attemptId,userId,isAdmin=false){const exam=await detail(examId,userId,isAdmin);if(!exam)return null;const data=await repo.findAttemptForTeacher(examId,attemptId);if(!data)return null;data.essayQuestions=data.exam.questions.filter(q=>q.questionType==='ESSAY');return data;}
async function manualGrade(examId,attemptId,userId,body,isAdmin=false){const data=await gradeForm(examId,attemptId,userId,isAdmin);if(!data)throw new Error('ATTEMPT_NOT_FOUND');const grades=data.exam.questions.filter(q=>q.questionType==='ESSAY').map(q=>({questionId:q.id,awardedScore:body[`score_${q.id}`],teacherFeedback:clean(body[`feedback_${q.id}`])}));return repo.manualGradeAttempt(examId,attemptId,userId,grades);}
module.exports={list,newForm,create,update,detail,publish,close,studentList,start,attempt,saveAnswer,submit,gradeForm,manualGrade};
