const express=require('express');
const controller=require('./exam.controller');
const {requireRole,requireApiRole}=require('../../middleware/auth.middleware');
const web=express.Router();
web.get('/exams',requireRole('TEACHER','ADMIN'),controller.index);
web.get('/exams/new',requireRole('TEACHER','ADMIN'),controller.newForm);
web.post('/exams',requireRole('TEACHER','ADMIN'),controller.create);
web.get('/exams/:id/edit',requireRole('TEACHER','ADMIN'),controller.editForm);
web.post('/exams/:id/update',requireRole('TEACHER','ADMIN'),controller.update);
web.get('/exams/:id',requireRole('TEACHER','ADMIN'),controller.detail);
web.post('/exams/:id/publish',requireRole('TEACHER','ADMIN'),controller.publish);
web.post('/exams/:id/close',requireRole('TEACHER','ADMIN'),controller.close);
web.get('/student/exams',requireRole('STUDENT'),controller.studentIndex);
web.post('/student/exams/:id/start',requireRole('STUDENT'),controller.start);
web.get('/student/exam-attempts/:id',requireRole('STUDENT'),controller.attempt);
web.post('/student/exam-attempts/:id/submit',requireRole('STUDENT'),controller.submit);
web.get('/student/exam-attempts/:id/result',requireRole('STUDENT'),controller.result);
const api=express.Router();
api.post('/exam-attempts/:id/answers',requireApiRole('STUDENT'),controller.apiSaveAnswer);
module.exports={web,api};
